import {
  SiAccuweather,
  SiAndroid,
  SiBluetooth,
  SiBrave,
  SiDiscord,
  SiDuolingo,
  SiEbay,
  SiFacebook,
  SiFirefox,
  SiFortnite,
  SiGmail,
  SiGoogle,
  SiGooglecalendar,
  SiGooglechrome,
  SiGoogledrive,
  SiGooglemaps,
  SiGooglepay,
  SiGooglephotos,
  SiGoogleplay,
  SiInstagram,
  SiKakaotalk,
  SiLine,
  SiMessenger,
  SiNetflix,
  SiNfc,
  SiOpera,
  SiPaypal,
  SiPinterest,
  SiSamsung,
  SiShazam,
  SiSignal,
  SiSnapchat,
  SiSpotify,
  SiSupercell,
  SiTelegram,
  SiTiktok,
  SiUber,
  SiViber,
  SiWhatsapp,
  SiX,
  SiXiaomi,
  SiYoutube,
  SiYoutubemusic,
} from '@icons-pack/react-simple-icons';
import type { ComponentType } from 'react';

type IconComponent = ComponentType<{ size?: number; color?: string; title?: string }>;

export const APP_ICON_MAP: Record<string, IconComponent> = {
  // Facebook
  'com.facebook.katana': SiFacebook,
  'com.facebook.orca': SiMessenger,
  'com.facebook.lite': SiFacebook,
  // Instagram
  'com.instagram.android': SiInstagram,
  'com.instagram.lite': SiInstagram,
  // Twitter/X
  'com.twitter.android': SiX,
  // TikTok
  'com.tiktok.android': SiTiktok,
  'com.zhiliaoapp.musically': SiTiktok,
  // Snapchat
  'com.snapchat.android': SiSnapchat,
  // LinkedIn
  'com.linkedin.android': SiGoogle,
  // Pinterest
  'com.pinterest': SiPinterest,
  // Microsoft (simple-icons nao tem Microsoft)
  'com.microsoft.skydrive': SiGoogle,
  'com.microsoft.office.outlook': SiGoogle,
  'com.microsoft.teams': SiGoogle,
  'com.microsoft.office.word': SiGoogle,
  'com.microsoft.office.excel': SiGoogle,
  'com.microsoft.office.powerpoint': SiGoogle,
  'com.microsoft.office.onenote': SiGoogle,
  'com.officemobile': SiGoogle,
  'com.microsoft.emmx': SiGoogle,
  // Spotify
  'com.spotify.music': SiSpotify,
  // Netflix
  'com.netflix.mediaclient': SiNetflix,
  // Amazon
  'com.amazon.mShop.android.shopping': SiGoogle,
  'com.amazon.appmanager': SiGoogle,
  'com.amazon.ags.app': SiGoogle,
  'com.amazon.avod': SiGoogle,
  'com.amazon.dee.app': SiGoogle,
  // eBay
  'com.ebay.mobile': SiEbay,
  // PayPal
  'com.paypal.android.p2pmobile': SiPaypal,
  // Games
  'com.king.candycrushsaga': SiSupercell,
  'com.king.candycrushsodasaga': SiSupercell,
  'com.supercell.clashofclans': SiSupercell,
  'com.supercell.clashroyale': SiSupercell,
  'com.supercell.brawlstars': SiSupercell,
  'com.epicgames.fortnite': SiFortnite,
  // Google
  'com.google.android.gms': SiGoogle,
  'com.google.android.gmsquick': SiGoogle,
  'com.google.android.gm': SiGmail,
  'com.google.android.apps.maps': SiGooglemaps,
  'com.google.android.youtube': SiYoutube,
  'com.google.android.apps.youtube.music': SiYoutubemusic,
  'com.google.android.apps.docs': SiGoogledrive,
  'com.google.android.apps.photos': SiGooglephotos,
  'com.google.android.apps.chromecast.app': SiGoogle,
  'com.google.android.apps.nexuslauncher': SiAndroid,
  'com.google.android.inputmethod.latin': SiGoogle,
  'com.google.android.googlequicksearchbox': SiGoogle,
  'com.google.android.apps.walletnfcrel': SiGooglepay,
  'com.google.android.calendar': SiGooglecalendar,
  'com.google.android.contacts': SiGoogle,
  'com.google.android.dialer': SiGoogle,
  'com.google.android.apps.messaging': SiGoogle,
  'com.google.android.marvin.talkback': SiAndroid,
  'com.google.android.accessibility.switchaccess': SiAndroid,
  'com.google.android.projection.gearhead': SiAndroid,
  // Samsung
  'com.sec.android.app.sbrowser': SiSamsung,
  'com.samsung.android.calculator': SiSamsung,
  'com.samsung.android.calendar': SiSamsung,
  'com.samsung.android.camera': SiSamsung,
  'com.samsung.android.app.tips': SiSamsung,
  'com.samsung.android.visionintelligence': SiSamsung,
  'com.samsung.android.bixby.agent': SiSamsung,
  'com.samsung.android.game.gamehome': SiSamsung,
  'com.sec.android.app.shealth': SiSamsung,
  // Xiaomi/MIUI
  'com.miui.home': SiXiaomi,
  'com.miui.securitycenter': SiXiaomi,
  'com.miui.gallery': SiXiaomi,
  'com.miui.calculator': SiXiaomi,
  'com.miui.cleaner': SiXiaomi,
  'com.miui.weather2': SiXiaomi,
  'com.miui.mishare.connectivity': SiXiaomi,
  // Communication
  'com.whatsapp': SiWhatsapp,
  'com.whatsapp.w4b': SiWhatsapp,
  'org.telegram.messenger': SiTelegram,
  'org.thoughtcrime.securesms': SiSignal,
  'com.viber.voip': SiViber,
  'jp.naver.line.android': SiLine,
  'com.discord': SiDiscord,
  'com.skype.raider': SiGoogle,
  // Browsers
  'org.mozilla.firefox': SiFirefox,
  'com.opera.browser': SiOpera,
  'com.opera.mini.native': SiOpera,
  'com.brave.browser': SiBrave,
  // Utilities
  'com.duolingo': SiDuolingo,
  'com.shazam.android': SiShazam,
  'com.accuweather.android': SiAccuweather,
  'com.ubercab': SiUber,
  'com.grabtaxi.driver': SiGoogle,
  'com.grabtaxi.passenger': SiGoogle,
  'com.kakao.taxi': SiKakaotalk,
  // Android System
  'com.android.vending': SiGoogleplay,
  'com.android.settings': SiAndroid,
  'com.android.systemui': SiAndroid,
  'com.android.phone': SiAndroid,
  'com.android.contacts': SiAndroid,
  'com.android.mms': SiAndroid,
  'com.android.dialer': SiAndroid,
  'com.android.launcher': SiAndroid,
  'com.android.launcher3': SiAndroid,
  'com.android.providers.storage': SiAndroid,
  'com.android.server.telecom': SiAndroid,
  'com.android.bluetooth': SiBluetooth,
  'com.android.nfc': SiNfc,
  'com.android.certinstaller': SiAndroid,
  'com.android.chrome': SiGooglechrome,
  'com.android.camera': SiAndroid,
  'com.android.gallery3d': SiAndroid,
  'com.android.calendar': SiAndroid,
  'com.android.deskclock': SiAndroid,
  'com.android.calculator2': SiAndroid,
  'com.android.email': SiAndroid,
  'com.android.filemanager': SiAndroid,
  'com.android.inputmethod.latin': SiAndroid,
  'com.android.music': SiAndroid,
  'com.android.soundrecorder': SiAndroid,
  'com.android.term': SiAndroid,
  'com.android.webview': SiGooglechrome,
  'com.android.packageinstaller': SiAndroid,
  'com.android.stk': SiAndroid,
  'com.android.wallpaper.live': SiAndroid,
  'com.android.providers.downloads': SiAndroid,
  'com.android.providers.downloads.ui': SiAndroid,
  'com.android.providers.media': SiAndroid,
  'com.android.providers.userdictionary': SiAndroid,
  'com.android.quicksearchbox': SiGoogle,
  'com.android.se': SiAndroid,
  'com.android.shell': SiAndroid,
  'com.android.traceur': SiAndroid,
  'com.android.wallpapercropper': SiAndroid,
};
