export const CRITICAL_PACKAGES = new Set([
  'com.android.vending',
  'com.android.settings',
  'com.android.systemui',
  'com.android.providers.storage',
  'com.android.phone',
  'com.android.server.telecom',
  'com.google.android.gms',
  'com.google.android.gmsquick',
  'com.android.launcher',
  'com.android.launcher3',
  'com.android.dialer',
  'com.android.contacts',
  'com.android.mms',
]);

export const BLOATWARE_PACKAGES = new Set([
  'com.facebook.katana',
  'com.facebook.appmanager',
  'com.facebook.services',
  'com.facebook.system',
  'com.instagram.android',
  'com.microsoft.skydrive',
  'com.microsoft.office.outlook',
  'com.microsoft.teams',
  'com.linkedin.android',
  'com.twitter.android',
  'com.snapchat.android',
  'com.tiktok.android',
  'com.pinterest',
  'com.spotify.music',
  'com.netflix.mediaclient',
  'com.amazon.mShop.android.shopping',
  'com.ebay.mobile',
  'com.paypal.android.p2pmobile',
  'com.king.candycrushsaga',
  'com.supercell.clashofclans',
  'com.duolingo',
  'com.shazam.android',
  'com.accuweather.android',
  'com.borderfree',
  'com.officemobile',
]);

export const APP_LABELS: Record<string, string> = {
  'com.facebook.katana': 'Facebook',
  'com.facebook.appmanager': 'Facebook App Manager',
  'com.facebook.services': 'Facebook Services',
  'com.facebook.system': 'Facebook System',
  'com.facebook.orca': 'Messenger',
  'com.instagram.android': 'Instagram',
  'com.twitter.android': 'Twitter',
  'com.tiktok.android': 'TikTok',
  'com.snapchat.android': 'Snapchat',
  'com.linkedin.android': 'LinkedIn',
  'com.pinterest': 'Pinterest',
  'com.spotify.music': 'Spotify',
  'com.netflix.mediaclient': 'Netflix',
  'com.microsoft.skydrive': 'OneDrive',
  'com.microsoft.office.outlook': 'Outlook',
  'com.microsoft.teams': 'Teams',
  'com.officemobile': 'Office Mobile',
  'com.amazon.mShop.android.shopping': 'Amazon',
  'com.ebay.mobile': 'eBay',
  'com.paypal.android.p2pmobile': 'PayPal',
  'com.king.candycrushsaga': 'Candy Crush',
  'com.supercell.clashofclans': 'Clash of Clans',
  'com.duolingo': 'Duolingo',
  'com.shazam.android': 'Shazam',
  'com.accuweather.android': 'AccuWeather',
  'com.borderfree': 'Borderfree',
  'com.android.vending': 'Google Play Store',
  'com.android.settings': 'Settings',
  'com.android.systemui': 'System UI',
  'com.android.phone': 'Phone',
  'com.android.contacts': 'Contacts',
  'com.android.mms': 'Messages',
  'com.android.dialer': 'Dialer',
  'com.android.launcher': 'Launcher',
  'com.android.launcher3': 'Launcher',
  'com.google.android.gms': 'Google Play Services',
  'com.google.android.gmsquick': 'Google Play Services',
  'com.android.providers.storage': 'Storage',
  'com.android.server.telecom': 'Telecom',
};

export const PRESETS = {
  minimal: {
    name: 'Minimal',
    description: 'Redes sociais e jogos',
    packages: [
      'com.facebook.katana',
      'com.facebook.appmanager',
      'com.facebook.services',
      'com.facebook.system',
      'com.instagram.android',
      'com.tiktok.android',
      'com.snapchat.android',
      'com.king.candycrushsaga',
      'com.supercell.clashofclans',
    ],
  },
  recommended: {
    name: 'Recomendado',
    description: 'Essencial + nuvem e entretenimento',
    packages: [
      'com.facebook.katana',
      'com.facebook.appmanager',
      'com.facebook.services',
      'com.facebook.system',
      'com.instagram.android',
      'com.tiktok.android',
      'com.snapchat.android',
      'com.king.candycrushsaga',
      'com.supercell.clashofclans',
      'com.microsoft.skydrive',
      'com.microsoft.office.outlook',
      'com.microsoft.teams',
      'com.linkedin.android',
      'com.twitter.android',
      'com.pinterest',
      'com.spotify.music',
      'com.netflix.mediaclient',
      'com.duolingo',
    ],
  },
  performance: {
    name: 'Performance',
    description: 'Máximo possível',
    packages: [
      'com.facebook.katana',
      'com.facebook.appmanager',
      'com.facebook.services',
      'com.facebook.system',
      'com.instagram.android',
      'com.tiktok.android',
      'com.snapchat.android',
      'com.king.candycrushsaga',
      'com.supercell.clashofclans',
      'com.microsoft.skydrive',
      'com.microsoft.office.outlook',
      'com.microsoft.teams',
      'com.linkedin.android',
      'com.twitter.android',
      'com.pinterest',
      'com.spotify.music',
      'com.netflix.mediaclient',
      'com.duolingo',
      'com.amazon.mShop.android.shopping',
      'com.ebay.mobile',
      'com.paypal.android.p2pmobile',
      'com.shazam.android',
      'com.accuweather.android',
      'com.borderfree',
      'com.officemobile',
    ],
  },
} as const;

export type PresetKey = keyof typeof PRESETS;

export function getAppLabel(packageName: string): string {
  return APP_LABELS[packageName] || packageName.split('.').pop() || packageName;
}
